version: '3.8'

services:
  # سرویس فرانت‌اند Next.js
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api
    depends_on:
      - server
    networks:
      - tour-network
    restart: unless-stopped

  # سرویس سرور Express
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/tour_management
      - JWT_SECRET=travel_manager_super_secret_key_123456
      - TOKEN_EXPIRY=7d
    depends_on:
      - mongodb
    volumes:
      - ./uploads:/app/uploads
    networks:
      - tour-network
    restart: unless-stopped

  # سرویس دیتابیس MongoDB
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - tour-network
    restart: unless-stopped

# شبکه‌های مورد استفاده
networks:
  tour-network:
    driver: bridge

# ولوم‌های مورد استفاده
volumes:
  mongodb_data:
    driver: local
